version: '3.8'

services:
  travel-planner:
    build: .
    container_name: travel-planner
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - travel-network
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      - ./logs:/var/log/nginx

networks:
  travel-network:
    driver: bridge
